name: Periodic health check

on:
  schedule:
    - cron: '1 * * * *' # Run at every first minute of every hour

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: periodic health check
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://damp-atoll-21040.herokuapp.com/health/
          max-attempts: 2
          retry-delay: 5s
