name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    env:
      SKIP_DEPLOY: ${{ contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: echo SKIP_DEPLOY
        run: echo ${{ env.SKIP_DEPLOY }}
      - name: echo not SKIP_DEPLOY
        run: echo ${{ !env.SKIP_DEPLOY }}
      - name: echo event_name == push
        run: echo ${{ github.event_name == 'push' }}
      - name: echo push AND skip
        run: echo ${{ (github.event_name == 'push') && !env.SKIP_DEPLOY}}
      - name: testing skip_deploy without env
        run: echo ${{ !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    outputs:
      SKIP_DEPLOY: ${{ env.SKIP_DEPLOY }}

  test_tags:
    needs: a_test_job
    runs-on: ubuntu-20.04
    steps:
      - run: echo ${{ needs.a_test_job.outputs.SKIP_DEPLOY }}
