name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: testing commit skip
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          SKIP_DEPLOY: ${{ contains(join(env.COMMIT_MESSAGES), '#skip') }}
        run: echo ${{ env.SKIP_DEPLOY}}; echo ${{ github.event_name == 'push' }}; echo ${{github.event_name == 'push' && !env.SKIP_DEPLOY}}
    outputs:
      SKIP_DEPLOY: ${{ env.SKIP_DEPLOY }}

  test_tags:
    needs: [a_test_job]
    runs-on: ubuntu-20.04
    steps:
      - run: echo ${{ needs.simple_deployment_pipeline.SKIP_DEPLOY }}
